// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcd9J_ImUItSbBxbI4gC4tTWQxFVU7fxY',
    appId: '1:892626383124:web:2794b667723fa0f5291201',
    messagingSenderId: '892626383124',
    projectId: 'homanager-app',
    authDomain: 'homanager-app.firebaseapp.com',
    storageBucket: 'homanager-app.appspot.com',
    measurementId: 'G-S70SWMKJ45',
    databaseURL: 'https://homanager-app-default-rtdb.firebaseio.com/'
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiJflnv_E4c5uVciPFY_pLG_xjWdkQG2I',
    appId: '1:892626383124:android:c82bc0efdc5e1c8e291201',
    messagingSenderId: '892626383124',
    projectId: 'homanager-app',
    storageBucket: 'homanager-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtuOqu0lWMG0Sd3YUPtzFUD9ckakpTpM4',
    appId: '1:892626383124:ios:f70eb4e157c93d6a291201',
    messagingSenderId: '892626383124',
    projectId: 'homanager-app',
    storageBucket: 'homanager-app.appspot.com',
    iosBundleId: 'com.example.homanagerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtuOqu0lWMG0Sd3YUPtzFUD9ckakpTpM4',
    appId: '1:892626383124:ios:919fc91b0cd0ea72291201',
    messagingSenderId: '892626383124',
    projectId: 'homanager-app',
    storageBucket: 'homanager-app.appspot.com',
    iosBundleId: 'com.example.homanagerApp.RunnerTests',
  );
}
